# Generated by Django 5.0.6 on 2024-05-13 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boatname', models.CharField(max_length=25)),
                ('boatimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('boatdailyprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unavailabilityperiod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudboat.unavailability')),
            ],
        ),
    ]
