# Generated by Django 5.0.6 on 2024-05-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudboat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='unavailabilityperiod',
            new_name='unavailability',
        ),
    ]
