# Generated by Django 5.0.6 on 2024-05-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudboat', '0002_rename_unavailabilityperiod_holiday_unavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='unavailability',
        ),
        migrations.AddField(
            model_name='holiday',
            name='unavailability',
            field=models.ManyToManyField(to='crudboat.unavailability'),
        ),
    ]
