# Generated by Django 5.0.6 on 2024-05-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudboat', '0004_alter_holiday_boatimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='boatimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
